[loggers]
keys=root, uvicorn

[handlers]
keys=custom_handler

[formatters]
keys=custom_json

[logger_root]
level=INFO
handlers=custom_handler
propagate=1

[logger_uvicorn]
level=INFO
handlers=custom_handler
propagate=0
qualname=uvicorn

[handler_custom_handler]
class=logging.StreamHandler
formatter=custom_json
args=()

[formatter_custom_json]
class=app.logger.CustomJsonFormatter
