services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ../
      target: local
      args:
        - APP_NAME=app
    container_name: app
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    env_file:
      - ../.env
    environment:
      - CORE_MQ_KAFKA_BROKERS=kafka:29092
    # Mount source for hot reload in container
    volumes:
      - ../app:/app/app
    ports:
      - "3000:8080"
    networks:
      - app

  kafka:
    image: apache/kafka:3.9.0
    hostname: kafka
    container_name: app-kafka
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    networks:
      - app

  kafka-ui:
    image: kafbat/kafka-ui
    container_name: app-kafka-ui
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: app-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - app
    depends_on:
      kafka:
        condition: service_healthy

networks:
  app:
    driver: bridge